### ISSUE TITLE
Bug: iOS sign-up & log in

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#131]
There are some problems with iOS sign-up. 

1. Clicking Google sign-in causes crash.
2. When logging in if you haven't signed up yet then there is some gibberish text.
3. On the following screen when you want to type in your user name and password, the submit button doesn't work. You have to click done before being able to submit.

**Comment by 7flash** [comment]
https://github.com/HighVibe/hvn/pull/138
