### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by 7flash** [HighVibe/hvn#136]
1) "Create Playlist" on profile/current_user
2) "Add to Playlist" on audio_player
3) "Edit Playlist" on profile/playlists

**Comment by 7flash** [comment]
Allow to combine audios from multiple authors into single playlist

Allow to cut audios by setting boundaries(start and end)

Create playlists: Working Background, Meditating, etc..

**Comment by minikin** [comment]
@7flash 

"Allow to cut audios by setting boundaries(start and end)" should be moved to separate tasks.

**Comment by minikin** [comment]
@JasonHighVibe Can you point me out to the latest design for the "Manage Playlist" flow, please?
