### ISSUE TITLE
Upload Audio

### ISSUE THREAD

**Issue by 7flash** [HighVibe/hvn#137]
┆Issue is synchronized with this [Jira Task](https://highvibe.atlassian.net/browse/HVN1-131) by [Unito](https://www.unito.io/learn-more)

**Comment by JasonHighVibe** [comment]
Updating so we can finalize this this week.

User can upload content from the small menu on their profile (small blue and white plus sign)

Once in the upload flow, they will select file (from native file browser).

While the file is uploading they will be taken to the Edit Info screen where they can choose name, description, and tag their content. 

![Group 2548](https://user-images.githubusercontent.com/63387665/86558872-2200e780-bf8d-11ea-93a8-17dd73af8d08.png)
![Group 2549](https://user-images.githubusercontent.com/63387665/86558876-24634180-bf8d-11ea-88f0-e714bc366a09.png)
![Group 2550](https://user-images.githubusercontent.com/63387665/86558877-24fbd800-bf8d-11ea-9a26-e73e78dc1aa3.png)
![Group 2551](https://user-images.githubusercontent.com/63387665/86558880-25946e80-bf8d-11ea-9ddc-dad2e7b4aad2.png)
![Group 2552](https://user-images.githubusercontent.com/63387665/86558884-262d0500-bf8d-11ea-91d4-2ad51e103b0a.png)
![Group 2553](https://user-images.githubusercontent.com/63387665/86558885-26c59b80-bf8d-11ea-9e0c-393476b91779.png)
![Group 2554](https://user-images.githubusercontent.com/63387665/86558886-275e3200-bf8d-11ea-808a-5531285b166d.png)
