### ISSUE TITLE
Update Project Name for "Forgot Password" Email Template

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#203]
**Describe the bug**
When a user selects forgot password, they receive an e-mail that shows a "Reset your password for project-468548202200" 
We should update this to say "Reset your password for HighVibe".

If we can have some customized design options for this screen let's design something for it as well. Post in the reply if this functionality is an option.

<img width="1079" alt="Screen Shot 2020-07-07 at 3 58 02 PM" src="https://user-images.githubusercontent.com/63387665/86742364-a5443b00-c06a-11ea-8811-2c8a40d74ba9.png">

**Comment by mob-dev** [comment]
I have updated the Project name in Firebase. I am closing this issue as it is fixed now.
