### ISSUE TITLE
Refined Login/Sign-up Flow

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#206]
User should have an option to choose the to Sign-up or Login option when they first sign-in to the application. 

We should also save whether or not they have logged in before. If they have, we should take them straight to login. If not, then they should have the option to.

Here is the complete flow:

1. Initiate the HighVibe App
2. Splash Screen
3. Mountain screen with option to Login OR Sign-up
if login -> goes to login flow
if Sign-up -> goes to sign-up flow

![Login or signup](https://user-images.githubusercontent.com/63387665/86911031-312e9380-c14d-11ea-8936-427155db35b1.png)

**Comment by mob-dev** [comment]
The PR #210 is merged, so we can close this issue.
