### ISSUE TITLE
Conditional Compilation

### ISSUE THREAD

**Issue by minikin** [HighVibe/hvn#264]
One of the big issues with Flutter for Web right now is its lack of support for `dart.io` and many flutter packages. 
This means things like a simple `Platform.isAndroid` the call will cause your web builds to crash on startup. 
In fact, just including the `dart.io` package _at all_ **will break your app completely.**

In cases like this, what is needed is some form of conditional compilation, so we can include the code on some platforms, 
and exclude it from others.

The raw idea of how to implement it is [here](https://stackoverflow.com/questions/58710226/how-to-import-platform-specific-dependency-in-flutter-dart-combine-web-with-an/58713064#58713064
).

**Comment by minikin** [comment]
Please, read issue description: @JasonHighVibe @7flash

**Comment by minikin** [comment]
@JasonHighVibe @7flash 
I tried to implement this yesterday to be able to merge [feature/sp-215](https://github.com/HighVibe/hvn/tree/feature/sp-215) branch into `master`.  I found out that we have one dependency [firebase 7.3.0](https://pub.dev/packages/firebase) which is not easy to isolate. And to do so will require enormous touchpoints of codebase modifications across the whole app. That's not what we want.

My proposal:
- Create a temporary branch for web-portal e.g. `web-portal`
- Keep `web-portal` branch in sync with the `master` branch
- Wait until [cloud_firestore](https://pub.dev/packages/cloud_firestore/versions/0.14.0-dev.1/example) will have a stable version for web support (it has a dev version now)
- Migrate to `cloud_firestore` from `firebase 7.3.0` for  `web-portal`
- Merge `web-porta`l into `master`

I'd appreciate it if you could share your opinion on that,
or share other ideas on how to deal with this problem with reasonable time and resource constraints.

**Comment by AlexVegner** [comment]
@minikin @JasonHighVibe @7flash 
https://pub.dev/packages/cloud_firestore have stable release 0.13.7 we neew to stick with it untill 0.14.x release. 
0.13.7 works for Web and Mobile. 
We need to migrate to cloud_firestore and merge web portal with master. 
All Firebase specific things mast be incapsulated on services layer.

**Comment by minikin** [comment]
@AlexVegner cloud_firestore doesn't support `html.File`. `dart:io` doesn't work flutter for the web. 
As a consequence, we can't convert  `html.File` to `File`.

**Comment by minikin** [comment]
At this issue, we just need to decide what to do with the `feature/sp-215` branch.
So @AlexVegner could clarify your proposal in detail, please? Just keep in mind that we have cross dependencies.

**Comment by AlexVegner** [comment]
@minikin 
Could you create PR eature/sp-215 to master I will review it?

**Comment by minikin** [comment]
@AlexVegner you should receive notification now.

>If you have not solution for download / upload files with cloud_firestore just add TODO, I believe we will find solution for it.

I would like to propose to fire an issue on GitHub instead of TODO.

**Comment by AlexVegner** [comment]
@minikin 
Sure,
I didn't found such issue on Github:
Please create new issue for cloud_firestore
https://github.com/FirebaseExtended/flutterfire/issues

**Comment by AlexVegner** [comment]
@JasonHighVibe @7flash
We just have conversation with Sasha @minikin 
And we agreed that I will research ability to upload files with cloud_firestore + file_picker. 
As a temperary solution Sasha @minikin  will use web-porta branch.

**Comment by JasonHighVibe** [comment]
Great sounds good 👌

**Comment by minikin** [comment]
[web-portal](https://github.com/HighVibe/hvn/tree/web-portal) branch has been created, documentation added to the [wiki](https://github.com/HighVibe/hvn/wiki/HVN-build-channel).

@JasonHighVibe @AlexVegner
