### ISSUE TITLE
Web Portal: Upload Flow Track Duration

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#269]
**Describe the bug**
Proper Track length isn't being displayed within the app on profile/webportal.

![ClipLengthBut1](https://user-images.githubusercontent.com/63387665/88505135-3161d680-d009-11ea-855f-2c76094707f9.png)
![CliipLengthbug2](https://user-images.githubusercontent.com/63387665/88505138-32930380-d009-11ea-9f92-f5c2b9b9b6a4.png)

**Comment by minikin** [comment]
@JasonHighVibe  Firebase function is not triggered. I'll fix it.

**Comment by minikin** [comment]
<img width="600" alt="Screenshot 2020-07-31 at 00 12 22" src="https://user-images.githubusercontent.com/4456735/88979753-9431c700-d2c2-11ea-8f58-188c3bba4069.png">
