### ISSUE TITLE
Discover Screen (Audio): Displaying Irrelevant Information

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#276]
In the Discover Screen, we are displaying non-relevant information.

We should only display the Title of the track as well as the Creator Name of the track.

![discoveraudiobug](https://user-images.githubusercontent.com/63387665/88760274-453f4100-d19f-11ea-92bc-1c3f76aeb976.jpg)

**Comment by JasonHighVibe** [comment]
Regarding this point, can we make sure to understand why some of the names are not displaying. @mob-dev

**Comment by JasonHighVibe** [comment]
Let's delete the files that do not have the proper formatting.

**Comment by mob-dev** [comment]
Jason, some of the audios have empty **"username"** values when they are coming from Firebase.
