### ISSUE TITLE
On user log out app crashes

### ISSUE THREAD

**Issue by minikin** [HighVibe/hvn#328]
**Describe the bug**
On user log out app crashes:

```sh
Exception has occurred.
PlatformException (PlatformException(Error 7, FIRFirestoreErrorDomain, Missing or insufficient permissions.))
```

@

`app_controller.dart`
```dart
  void _setUserOnline(bool active) {
    if (currentUser != null) {
      firestore.userCollection.document(currentUser.id).updateData({
        'isOnline': active,
        // "lastTimeSeen": serializers.serialize(DateTime.now().toUtc())
      });
    }
  }
```

**To Reproduce**
1. Press log out the user

**Smartphone:**
 -  iPhone SE2
 - iOS 13.6

┆Issue is synchronized with this [Jira Task](https://highvibe.atlassian.net/browse/HVN1-184) by [Unito](https://www.unito.io/learn-more)

**Comment by AlexVegner** [comment]
Duplicate to #329. Closed.
