### ISSUE TITLE
Update GT creation flow

### ISSUE THREAD

**Issue by minikin** [HighVibe/hvn#399]
- [x] Select and set Bell Sound
- [x]  Error handling (e.g. sum of intervals can't be longer than total duration)
- [x] Update time formater to display hours if  hours are available

┆Issue is synchronized with this [Jira Task](https://highvibe.atlassian.net/browse/HVN1-254) by [Unito](https://www.unito.io/learn-more)

**Comment by JasonHighVibe** [comment]
Bell sounds:

https://drive.google.com/drive/folders/1yp9gLH1X13JGsMtODtnrJxjAraCgT6K0?usp=sharing
