### ISSUE TITLE
Livestream integration

### ISSUE THREAD

**Issue by vladimircores** [HighVibe/hvn#402]
**Outcome**
1. User can start live stream from UI - Broadcaster
2. Live stream video from front camera displayed fullscreen in portrait mode with few buttons overlays
3. Broadcaster can leave the stream by:
- clicking button on screen, 
- back navigation or 
- when app closed

┆Issue is synchronized with this [Jira Task](https://highvibe.atlassian.net/browse/HVN1-257) by [Unito](https://www.unito.io/learn-more)

**Comment by JasonHighVibe** [comment]
Simplified Flow:


![Live! 1  Go Live](https://user-images.githubusercontent.com/63387665/93843461-7d10c380-fccc-11ea-8e9d-6b534b3b7b12.png)

User will be be able to add title and description before selecting to "Go Live". We are adding a field for the title to also be added.
![Live! 2  Add Description](https://user-images.githubusercontent.com/63387665/93843468-826e0e00-fccc-11ea-8c21-8fd34d08f41d.png)
![Live! 3  Add Description Type](https://user-images.githubusercontent.com/63387665/93843470-839f3b00-fccc-11ea-83a9-197c25aa2232.png)

I think it would be a great flow if a picture is taken once the user selects to "Go Live" that will be used as a preview picture in Discover.

Once live, the Chat will pop up and people will be able to communicate with the Creator.
![Live! 9  Connect Live - LiVE! (2)](https://user-images.githubusercontent.com/63387665/93843473-8568fe80-fccc-11ea-8506-be034f888319.png)
