### ISSUE TITLE
Livestream - More Info

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#42]
Objective:
Users will be able to see additional information about the livestream while watching the Livestream. Statistics like # of Live Viewers, Time Live, Location, More Info.

Purpose:
To give users an easy way to understand what it is they are watching.

**Comment by 7flash** [comment]
Also have a live discussion for each chat - so they can understand even without listening

**Comment by JasonHighVibe** [comment]
Can you clarify? i think if they're watching the livestream the only way to know what's going on is either through the chat feature (type based), and then communicate later through the forum/tribe chat area

**Comment by 7flash** [comment]
Yes, that's what I mean
