### ISSUE TITLE
Channel Chat/Communication

### ISSUE THREAD

**Issue by 7flash** [HighVibe/hvn#48]
**Outcome**
Enable chat functionality for each tribe outside of live streaming, even when author is not online, followers are still able to communicate in chat

**Purpose**
Create stronger feeling of community and exchange of knowledge around specific teacher or topic

**Comment by 7flash** [comment]
Currently, spiritual teachers have groups on facebook and then have opportunity to start broadcasting as separate feature in facebook. This is not optimal approach. We don't need wall with separate posts and comments for each post, and instead we apply Telegram approach of channels/chats. You have to follow teacher, and then you have access to channel messages and can participate in discussions in real time. You will be notified when teacher is going live. In explorer tab, you can explore different available teachers and you can start following (in some cases needed approval) and then you have access to chat and all materials available shared by members. Author of channel has special privileges. Sorry for lack of clarity in this description, but shortly, we prefer Telegram approach over Facebook approach and we combine best of both to provide most efficient and pleasurable way to share knowledge.

**Comment by JasonHighVibe** [comment]
Yes this makes sense. i think we can do something interesting here with the "Chat Channel"; it could also include certain activities done by the creator... Just brainstorming here but I'll try and expain:

XXXXXXX Tribe Channel XXXXXXXX

11:15PM **Creator started Livestream**
-----------------
12:20PM **Creator Finished Livestream**
12:23PM Debbie1529: Wow that was such a great stream! I just have a few questions that I just thought of....
12:24PM Creator: Sure how can I help?
12:25PM What's the meaning of life?
12:25PM Well here I can direct you to my past video where I already addressed it <Insert Link>

The idea being that there is a continues stream of what the Creator is doing in his Tribe (Maybe have filters to sort by Chats only/ Activites Only)

I don't want to complicate it but I want it to be clean and make sense

**Comment by 7flash** [comment]
Exactly, communication with Creator should be continued after live streaming finished
