### ISSUE TITLE
"Quote of the Day" or "Quote of the Week"

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#59]
Objective:
Users will see a quote at the top of their homescreen once they login/sign-up.

<img width="227" alt="Home Screen - Main" src="https://user-images.githubusercontent.com/63387665/79539565-2cf85a00-80b9-11ea-9aa6-8a92bab2f029.png">

Purpose:
Give users a stimulating quote the moment they enter into the App. Creates common ground amongst all of the users. on the App.

**Comment by 7flash** [comment]
Picture with design is not being displayed

**Comment by JasonHighVibe** [comment]
fixed

**Comment by JasonHighVibe** [comment]
Fixed.
