### ISSUE TITLE
Earn Karma Points

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#60]
Objective:
Users will earn Karma Points for contributing to the community by posting content, sharing live content, as well as the impact they gain from other users on the network. Full list as follows:

1. Earned Impact: Authors and curators earn K from users upvoting/liking their content.
2. Engagement aka Completing Experiences: Authors earn K when users complete
experiences
3. Going Live: # of users watching livestream, Level of engagement during stream: # of comments? 
3. Curating/Recommending/Sharing: Curators earn K based on traffic, subscriptions, and
engagement

How Karma is converted into HV is based on a member’s individual karma (IndK) that
day, the total karma available to the network that day (NetK), and the value of the Karma
daily rewards pool (Rk). “Individual” Karma (IndK): Karma earned by one user/author/creator in a given day 
IndK = {K(upvotes) + K(comments) + K(shares) + K(content) + K(Gifts)}
“Network” Karma (NetK) = Sum of all Karma earned on network in a given day
NetK = ΣIndK

Thus, the HV a member can earn in a given day from Karma is:
HV = (IndK/NetK) / Rk
Rk = Daily Rewards Pool Allocation for K

Purpose:
To incentivize content creation, going live, and contributing to the network.

**Comment by 7flash** [comment]
This will be implemented in smart contract

**Comment by 7flash** [comment]
Upvotes and comments will be implemented with firebase, but Karma points still will be implemented on blockchain. Oracle service will be watching daily statistics (from firebase) and issue Karma points to users accordingly (in smart contract).

**Comment by JasonHighVibe** [comment]
https://docs.google.com/spreadsheets/d/1MB48yAn-9iUhjvllHUmAjKS5_RGlv0rcjoLSfQIO65M/edit?usp=sharing
Check spreadsheet for assigned ratios of different actions on Platform.

We can greatly simplify this in the beginning.
