### ISSUE TITLE
Daily Rewards System

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#61]
Objective:
Users will earn Daily Rewards based on their XP/Karma generated per day in relation to the total amount of XP/Karma was generated in ecosystem in Total. See #60 and #25.

**Comment by JasonHighVibe** [comment]
![HighVibe_TokenomicsOverview](https://user-images.githubusercontent.com/63387665/79428678-14c10600-7ff9-11ea-8541-b1d85b93f08a.png)

**Comment by 7flash** [comment]
Here is out ethereum token:
https://etherscan.io/token/0x141abb03f001deded9a0223d4ff26d929117b72e

telos token will be deployed soon
