### ISSUE TITLE
Profile (Self/Owner's View):

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#63]
Objective:
Users will be able to see all specific information, stats and content through their own profile page. This includes:

1. HVN URL/Username

2. Swag Badges Earned

3. Statistics: Experience Points Earned, Followers, Hrs Streamed

4. Upcoming Streams, Past Streams (Scheduling aspect)

5. Other content ("Meditations", "Podcasts") 

6. Following (which profiles/creators the user is following - editing within)

7. Saved Playlists (UX/UI still have to be updated to reflect this)

8. Their own community Forum/Chat

See:
<img width="219" alt="Creator Profile (Self)" src="https://user-images.githubusercontent.com/63387665/79427295-feb24600-7ff6-11ea-8086-4b39d96a28cb.png">

**Comment by 7flash** [comment]
Creator
Content
Community

**Comment by JasonHighVibe** [comment]
Designed Screens are incoming early next week. Will need to iterate and improve the Profile/Creator Page.

**Comment by JasonHighVibe** [comment]
@minikin We have stripped down some of the feature-set but you can see here what our longterm goals for the profile are. Also some of the designs have changed as well.
