### ISSUE TITLE
Creator Page: Unique Page/Tab for Content

### ISSUE THREAD

**Issue by JasonHighVibe** [HighVibe/hvn#65]
**Outcome**
User can access the content on Creator's Profile. Creator can customize layout and organization of content and different type of contents. (Pictures, Video, Livestreaming, Text Posts)

**Purpose**
To allow the creator to create a dynamic and organized page for others to consume.

**Comment by 7flash** [comment]
Content being displayed in tiles - like instagram - but with difference that creator can move tiles around
